import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/components/LanguageProvider";
import { UserProvider } from "@/components/userProvider";
import { Toaster } from "@/components/ui/sonner"
import { TelegramProvider } from "@/components/TelegramProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <TelegramProvider>
            <LanguageProvider>
              {children}
            </LanguageProvider>
          </TelegramProvider>
        </UserProvider>
      </body>
    </html>
  );
}
